### PR TITLE
Add option to create PairList from AtomsBase structure

### PR DESCRIPTION
**Pull request by tjjarvinen**
This add simple inteface for AtomsBase structure.

```julia
nlist = PairList( atoms_base_system, 5.5u"Å" )
```

### CODE REVIEW

**Comment by cortner** [comment]
ready to review and merge?

**Comment by tjjarvinen** [comment]
Yes

**Comment by cortner** [comment]
and I assume this is a backward compatible extension

**Comment by cortner** [comment]
I think `runtests.jl ` need the new tests included.

**Comment by cortner** [comment]
Will the general registry accept the new version with CI enabled? We need to re-enable that at some point.

**Comment by tjjarvinen** [comment]
If none on dowstream has extended `PairList` with

```julia
PairList(ab::AtomsBase.AbstractSystem, cutoff::Unitful.Length; length_unit=unit(cutoff))
```

then yes. But, we can't be sure of it.

Added the test on runtime.

I am not sure about general registry, but it might need CI to be run.

**Comment by cortner** [comment]
I see so because we Are now iverloading with foreign types we need to make it a breaking change release, correct?

**Comment by tjjarvinen** [comment]
We are not beaking anything old, so it is not a breaking release.

But, if someone just happened to use that same overload, they could run to some problems.

Basically this is a new feature release and as just should be v0.5.6.

**Pull request merged**
