### PR TITLE
Modify types for ForwardDiff.jl compatibility

### PR DESCRIPTION
**Pull request by jamesgardner1421**
I was attempting to use NeighbourLists.jl with ForwardDiff.jl but ran into issues with the ForwardDiff dual types. With these changes it works without issue.

### CODE REVIEW

**Comment by cortner** [comment]
thank you - that's a great addition! Have you done any performance benchmarks?

**Comment by cortner** [comment]
Ignore that question, that's a really simple change to the typing - well done for spotting this!

**Comment by jamesgardner1421** [comment]
no worries, thanks for providing this package, has saved me a lot of time!

**Comment by cortner** [comment]
now tagged as `v0.5.2` in the [JuliaMolSim registry](https://github.com/JuliaMolSim/MolSim)

**Comment by cortner** [comment]
would you be interested in joining?

**Comment by jamesgardner1421** [comment]
joining JuliaMolSim? I could do. I had been considering contributing to JuLIP. I wanted to use this [EAM potential](https://link.springer.com/article/10.1007/s00894-020-04588-x) but couldn't figure out where to begin (I see that the currently implemented EAM is for only a single species).

If you could provide some direction on this I could try to add it.

**Comment by cortner** [comment]
that would be such a nice addition - I think most things are in place, it probably needs a file loader. I thought I put together some hack to let ASE load it and then just import the spline data .... anyhow - why don't you open an issue on `JuLIP.jl` and we go from there?

**Pull request merged**
